name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Calculater sematic version
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v0

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_HUB_USER_NAME }}/linuxtemperaturesensor:${{ steps.gitversion.outputs.semVer }}

    # Login and push to docker hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push the Docker image
      run: docker push ${{ vars.DOCKER_HUB_USER_NAME }}/linuxtemperaturesensor:${{ steps.gitversion.outputs.semVer }}

    